name: RSS update

on:
  schedule:
    # Runs at noon and midnight BRT every day (in theory)
    - cron: '0 3,15 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the permissions for the GITHUB_TOKEN for this workflow
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  fetch_and_deploy:
    runs-on: ubuntu-22.04
    env:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    steps:
      # Situation: we sometimes get an HTTP 404 error when `apt-get update`ing.
      # We need to run `apt-get upgrade` to solve that. But I've noticed Firefox
      # (comes preinstalled) takes a long while to upgrade. So we remove it first
      - name: Setup apt
        run: |
          sudo apt-get remove --purge firefox powershell && sudo apt-get autoremove
          sudo apt-get -y upgrade
          sudo apt-get update

      - name: Checkout repository
        uses: actions/checkout@v4

      - run: git pull

      - name: Fetch RSS feeds
        run: |
          python3 -m pip install -r ./scripts/requirements.txt
          python3 ./scripts/my-rss.py

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
